name: vhome_frontend
description: "vhome app"

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '^3.2.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  bloc: ^8.1.4
  vhome_web_api:
    path: packages/vhome_web_api
  vhome_repository:
    path: packages/vhome_repository
  rxdart: ^0.28.0
  intl: ^0.18.0
  formz: ^0.7.0
  file_selector_linux: ^0.9.2+1
  file_selector: ^1.0.3
  qr_flutter: ^4.1.0
  mobile_scanner: ^4.0.1
  shared_preferences: ^2.3.2
  flutter_dotenv: ^5.1.0
  screen_state: ^4.0.0
  syncfusion_flutter_charts: ^22.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/profile_picture.png
    - .env
