name: vhome_frontend
description: "vhome app"

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '^3.2.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  http: ^1.2.1
  flutter_session_manager: ^1.0.3
  
  riverpod_annotation: ^2.3.5
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  bloc: ^8.1.4
  vhome_web_api:
    path: packages/vhome_web_api
  vhome_repository:
    path: packages/vhome_repository
  rxdart: ^0.28.0
  intl: ^0.19.0
  tuple: ^2.0.2
  formz: ^0.7.0
  multi_dropdown: ^2.1.4
  image_picker: ^1.1.2
  file_selector_linux: ^0.9.2+1
  file_selector: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/profile_picture.png
